import type { Metadata } from 'next';
import { Be_Vietnam_Pro } from 'next/font/google';
import './globals.css';

const BeVietnamPro = Be_Vietnam_Pro({
	variable: '--font-main',
	subsets: ['latin'],
	weight: '500',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${BeVietnamPro.variable} antialiased`}>{children}</body>
		</html>
	);
}
